---
kong_version: "3.9.0"

kong_mode: "dbless"
# values:
# dbless
# postgres

kong_admin_listen: "127.0.0.1:8001"
kong_proxy_listen: "0.0.0.0:8000"

kong_pg_host: "127.0.0.1"
kong_pg_port: 5432
kong_pg_database: "kong"
kong_pg_user: "kong"
kong_pg_password: "kong"

backend_host: "127.0.0.1"
